[game]
chunk_size = [64, 64]
chunk_count = [36, 36]
padding = [1, 1]

[runtime]
period = 0
thread_count = 8
retry = 4

[gen]
unit_count = [10, 10]
mesh_size = 2

[log]
snapshot_paths.overview = ".\\log\\overview.png"

[bio]
initial_population = 100000
mutation.insert = 0.1
mutation.remove = 0.1

[bio.init]
wake_period = 10
wake_energy_consume = 1
energy_cost = 10000
spawn_loss = 9000
spawn_init_energy = 1000
incubation_delay = 10
size = [0, 0]
watch_period = 20
watch_area = 1
move_period = 1
move_cost = 10
eat_threshold = 10000
eat_takes = 1000
combat.hit_point = 100
combat.regeneration = 0
combat.regeneration_cost = 0
combat.atk = 0
combat.atk_cost = 0
combat.threat = 0
combat.flee_threshold = 0
combat.fight_back_threshold = 0
combat.chase_threshold = 0

[bio.acids.S]
mutate_rate = 300
[bio.acids.S.prop]
wake_period = 0.2
wake_energy_consume = 0.2
energy_cost = 5000
spawn_loss = 4500
spawn_init_energy = 500
incubation_delay = 0.2
size = [0.05, 0.05]
watch_period = 0
watch_area = 0.5
move_period = 0
move_cost = 2
eat_threshold = 0
eat_takes = 100
combat.hit_point = 20
combat.regeneration = 0.2
combat.regeneration_cost = 0
combat.atk = 0
combat.atk_cost = 0
combat.threat = 1
combat.flee_threshold = 0
combat.fight_back_threshold = 0
combat.chase_threshold = 0

[bio.acids.A]
mutate_rate = 300
[bio.acids.A.prop]
wake_period = -1
wake_energy_consume = 0.5
energy_cost = 2500
spawn_loss = 2250
spawn_init_energy = 250
incubation_delay = 0
size = [0, 0]
watch_period = -1
watch_area = 0
move_period = -0.2
move_cost = 0
eat_threshold = 0
eat_takes = 0
combat.hit_point = 0
combat.regeneration = 0
combat.regeneration_cost = 0
combat.atk = 1
combat.atk_cost = 0.25
combat.threat = 2
combat.flee_threshold = 1
combat.fight_back_threshold = 1
combat.chase_threshold = 1

[bio.acids.E]
mutate_rate = 100
[bio.acids.E.prop]
wake_period = 0
wake_energy_consume = 1
energy_cost = 20000
spawn_loss = 19000
spawn_init_energy = 1000
incubation_delay = 5
size = [0.05, 0.05]
watch_period = 1
watch_area = 15
move_period = 0
move_cost = 2
eat_threshold = 0
eat_takes = 100
combat.hit_point = 20
combat.regeneration = 0
combat.regeneration_cost = 0
combat.atk = 0
combat.atk_cost = 0
combat.threat = 0
combat.flee_threshold = 0
combat.fight_back_threshold = 0
combat.chase_threshold = 0

[bio.acids.D]
mutate_rate = 100
[bio.acids.D.prop]
wake_period = 0
wake_energy_consume = 1
energy_cost = 5000
spawn_loss = 4500
spawn_init_energy = 500
incubation_delay = 1
size = [0.05, 0.05]
watch_period = 0.5
watch_area = 1
move_period = 0
move_cost = 0
eat_threshold = -200
eat_takes = 200
combat.hit_point = 5
combat.regeneration = 0
combat.regeneration_cost = 0
combat.atk = 1
combat.atk_cost = 0.25
combat.threat = 2
combat.flee_threshold = 1
combat.fight_back_threshold = 1
combat.chase_threshold = 1

[bio.acids.P]
mutate_rate = 20
[bio.acids.P.prop]
wake_period = -1
wake_energy_consume = 2
energy_cost = 10000
spawn_loss = 9000
spawn_init_energy = 1000
incubation_delay = 0
size = [0.1, 0.1]
watch_period = 0
watch_area = 1
move_period = 0
move_cost = 1
eat_threshold = 500
eat_takes = 500
combat.hit_point = 20
combat.regeneration = 1
combat.regeneration_cost = 1
combat.atk = 10
combat.atk_cost = 2
combat.threat = 20
combat.flee_threshold = 25
combat.fight_back_threshold = 15
combat.chase_threshold = -20


[[bio.creatures]]
weight = 1
insertions = 0
gene = []
[[bio.creatures]]
weight = 1
insertions = 1
gene = []
[[bio.creatures]]
weight = 1
insertions = 2
gene = []
[[bio.creatures]]
weight = 1
insertions = 3
gene = []