[game]
chunk_size = [1, 1]
chunk_count = [9, 9]
padding = [1, 1]

[runtime]
period = 100
fire_tick = 4
thread_count = 4

[plant]
aging.possibility = 0.001
aging.growth = { grass = 10, tree = 20 }
sow.possibility = 0.00001
sow.items_weight = { grass = 9, tree = 1 }
fruit.cost = { grass = 40, tree = 100 }
fruit.threshold = { grass = 50, tree = 200 }

[plant.corpse]
rot = 20
convert_rate = 0.8