[game]
chunk_size = [1, 1]
chunk_count = [9, 9]
padding = [1, 1]

[runtime]
period = 100
thread_count = 4

[plant]
aging_possibility = 0.001
sow_possibility = 0.00001

[plant.grass]
grow = 10000
sow_weight = 9
fruit_cost = 20000
fruit_when = 50000

[plant.tree]
grow = 20000
sow_weight = 1
fruit_cost = 50000
fruit_when = 500000

[plant.corpse]
rot = 20
convert_rate = 0.8