[game]
chunk_size = [1, 1]
chunk_count = [9, 9]
padding = [1, 1]

[runtime]
period = 100
fire_tick = 4
plant_aging = 0.01
plant_sow = 0.001
plant_grow = 100
corpse_rot = 1
thread_count = 4
corpse_convert_cost = 1.0